local M = {}

local colors = require("fluovibe.palette")

M.setup = function()
	return {
		-- :h treesitter-highlight
		["@variable"]                          = { link = "Identifier" },
		["@variable.builtin"]                  = { fg = colors.purple },
		["@variable.parameter"]                = { fg = colors.orange },
		["@variable.member"]                   = { fg = colors.cyan },
		["@constant"]                          = { link = "Constant" },
		["@constant.builtin"]                  = { link = "Constant" },
		["@constant.macro"]                    = { link = "Constant" },
		["@module"]                            = { fg = colors.cyan },
		["@module.builtin"]                    = { fg = colors.purple },
		["@label"]                             = { link = "Keyword" },
		["@string"]                            = { link = "String" },
		["@string.documentation"]              = { link = "Keyword" },
		["@string.regexp"]                     = { fg = colors.red },
		["@string.escape"]                     = { link = "Keyword" },
		["@string.special"]                    = { link = "Constant" },
		["@string.special.symbol"]             = { link = "Constant" },
		["@string.special.url"]                = { link = "Underlined" },
		["@character"]                         = { link = "String" },
		["@character.special"]                 = { link = "Constant" },
		["@character.printf"]                  = { link = "Keyword" },
		["@type"]                              = { link = "Type" },
		["@type.builtin"]                      = { link = "Keyword" },
		["@type.definition"]                   = { link = "Type" },
		["@type.qualifier"]                    = { link = "Keyword" },
		["@function"]                          = { link = "Function" },
		["@function.builtin"]                  = { link = "Function" },
		["@function.call"]                     = { link = "Function" },
		["@function.macro"]                    = { link = "Function" },
		["@function.method"]                   = { link = "Function" },
		["@function.method.call"]              = { link = "Function" },
		["@constructor"]                       = { link = "Function" },
		["@operator"]                          = { link = "Keyword" },
		["@keyword"]                           = { link = "Keyword" },
		["@keyword.coroutine"]                 = { link = "Keyword" },
		["@keyword.function"]                  = { link = "Keyword" },
		["@keyword.operator"]                  = { link = "Keyword" },
		["@keyword.import"]                    = { link = "Keyword" },
		["@keyword.repeat"]                    = { link = "Keyword" },
		["@keyword.return"]                    = { link = "Keyword" },
		["@keyword.debug"]                     = { link = "Keyword" },
		["@keyword.exception"]                 = { link = "Keyword" },
		["@keyword.conditional"]               = { link = "Keyword" },
		["@keyword.conditional.ternary"]       = { link = "Keyword" },
		["@keyword.directive"]                 = { link = "Keyword" },
		["@keyword.directive.define"]          = { link = "Keyword" },
		["@punctuation.delimiter"]             = { link = "Delimiter" },
		["@punctuation.bracket"]               = { fg = colors.purple },
		["@punctuation.special"]               = { fg = colors.pink },
		["@comment"]                           = { link = "Comment" },
		["@comment.documentation"]             = { link = "Comment" },
		["@comment.error"]                     = { fg = colors.diag_error },
		["@comment.warning"]                   = { fg = colors.diag_warn },
		["@comment.todo"]                      = { fg = colors.yellow },
		["@comment.note"]                      = { fg = colors.cyan },
		["@markup.strong"]                     = { fg = colors.orange, bold = true },
		["@markup.italic"]                     = { fg = colors.yellow, italic = true },
		["@markup.strikethrough"]              = { fg = colors.comment },
		["@markup.underline"]                  = { fg = colors.cyan, underline = true },
		["@markup.heading"]                    = { fg = colors.cyan, bold = true },
		["@markup.quote"]                      = { fg = colors.comment },
		["@markup.math"]                       = { fg = colors.purple },
		["@markup.environment"]                = { fg = colors.comment },
		["@markup.link"]                       = { fg = colors.orange, bold = true },
		["@markup.link.label"]                 = { fg = colors.cyan, underline = true },
		["@markup.link.url"]                   = { fg = colors.cyan, underline = true },
		["@markup.raw"]                        = { fg = colors.comment },
		["@markup.raw.block"]                  = { fg = colors.fg },
		["@markup.list"]                       = { fg = colors.purple },
		["@markup.list.checked"]               = { fg = colors.git_add },
		["@markup.list.unchecked"]             = { fg = colors.git_change },
		["@diff.plus"]                         = { fg = colors.git_add },
		["@diff.minus"]                        = { fg = colors.git_delete },
		["@diff.delta"]                        = { fg = colors.git_change },
		["@tag"]                               = { fg = colors.yellow },
		["@tag.builtin"]                       = { link = "@tag" },
		["@tag.attribute"]                     = { fg = colors.pink },
		["@tag.delimiter"]                     = { fg = colors.yellow },
		["@property"]                          = { fg = colors.cyan },
	}
end

return M
