local M = {}

local colors = require("fluovibe.palette")

M.setup = function(opts)
	local transparent = opts.transparent
	local normal_bg = transparent and "NONE" or colors.bg
	local float_bg = transparent and "NONE" or colors.bg_dark
	local gutter_bg = transparent and "NONE" or colors.bg

	return {
		-- :h highlight-groups
		ColorColumn = { bg = colors.bg_dark },
		Conceal = { fg = colors.pink },
		CurSearch = { fg = colors.fg, bg = colors.selection },
		Cursor = { fg = colors.cursor_fg, bg = colors.cursor_bg },
		lCursor = { link = "Cursor" },
		CursorIM = { link = "Cursor" },
		CursorColumn = { link = "ColorColumn" },
		CursorLine = { bg = colors.cursorline },
		CursorLineNr = { fg = colors.pink, bg = gutter_bg },
		Directory = { fg = colors.yellow },
		DiffAdd = { fg = colors.git_add },
		DiffChange = { fg = colors.git_change },
		DiffDelete = { fg = colors.bg, bg = colors.git_delete },
		DiffText = { fg = colors.cyan, reverse = true },
		EndOfBuffer = { fg = colors.bg },
		TermCursor = { link = "Cursor" },
		TermCursorNC = { link = "Cursor" },
		ErrorMsg = { fg = colors.diag_error },
		WinSeparator = { fg = colors.separator, bg = float_bg },
		Folded = { fg = colors.comment, bg = colors.selection },
		FoldColumn = { fg = colors.fg, bg = gutter_bg },
		SignColumn = { bg = gutter_bg },
		IncSearch = { fg = colors.white, bg = colors.pink, bold = true },
		Substitute = { link = "IncSearch" },
		LineNr = { fg = colors.comment, bg = gutter_bg },
		LineNrAbove = { link = "LineNr" },
		LineNrBelow = { link = "LineNr" },
		CursorLineFold = { link = "FoldColumn" },
		CursorLineSign = { link = "SignColumn" },
		MatchParen = { fg = colors.diag_hint },
		ModeMsg = { link = "Normal" },
		MsgArea = { link = "Normal" },
		MsgSeparator = { link = "Normal" },
		MoreMsg = { fg = colors.cyan, bold = true },
		NonText = { fg = colors.comment },
		Normal = { fg = colors.fg, bg = normal_bg },
		NormalFloat = { fg = colors.fg, bg = float_bg },
		FloatBorder = { link = "WinSeparator" },
		FloatTitle = { link = "Title" },
		NormalNC = { link = "Normal" },
		Pmenu = { link = "NormalFloat" },
		PmenuSel = { bg = colors.selection },
		PmenuKind = { link = "Pmenu" },
		PmenuKindSel = { link = "PmenuSel" },
		PmenuExtra = { link = "Pmenu" },
		PmenuExtraSel = { link = "PmenuSel" },
		PmenuSbar = { link = "NormalFloat" },
		PmenuThumb = { bg = colors.pink },
		Question = { fg = colors.cyan, bold = true },
		QuickFixLine = { bg = colors.selection },
		Search = { link = "Visual" },
		SpecialKey = { fg = colors.yellow, bold = true },
		SpellBad = { fg = colors.diag_error, sp = colors.diag_error, underline = true },
		SpellCap = { fg = colors.diag_hint, sp = colors.diag_hint, underline = true },
		SpellLocal = { fg = colors.diag_info, sp = colors.diag_info, underline = true },
		SpellRare = { fg = colors.diag_warn, sp = colors.diag_warn, underline = true },
		StatusLine = { fg = colors.fg, bg = colors.bg_dark },
		StatusLineNC = { fg = colors.bg_dark, bg = colors.bg_dark },
		TabLine = { bg = colors.bg_dark },
		TabLineFill = { fg = colors.fg, bg = colors.bg_dark },
		TabLineSel = { fg = colors.yellow, bg = colors.bg },
		Title = { fg = colors.yellow, bold = true },
		Visual = { bg = colors.selection },
		VisualNOS = { link = "Visual" },
		WarningMsg = { fg = colors.diag_warn },
		Whitespace = { fg = colors.comment },
		WildMenu = { bg = colors.selection },
		WinBar = { link = "Pmenu" },
		WinBarNC = { link = "WinBar" },

		-- :h group-name
		Comment = { fg = colors.comment, italic = true },
		Constant = { fg = colors.purple },
		String = { fg = colors.purple },
		Character = { link = "String" },
		Number = { link = "Constant" },
		Boolean = { link = "Constant" },
		Float = { link = "Constant" },
		Identifier = { fg = colors.cyan },
		Function = { fg = colors.yellow },
		Statement = { link = "Keyword" },
		Conditional = { link = "Keyword" },
		Repeat = { link = "Keyword" },
		Label = { link = "Keyword" },
		Operator = { link = "Keyword" },
		Keyword = { fg = colors.pink },
		Exception = { link = "Keyword" },
		PreProc = { link = "Keyword" },
		Include = { link = "Keyword" },
		Define = { link = "Keyword" },
		Macro = { link = "Keyword" },
		PreCondit = { link = "Keyword" },
		Type = { fg = colors.purple },
		StorageClass = { link = "Keyword" },
		Structure = { link = "Type" },
		Typedef = { link = "Keyword" },
		Special = { fg = colors.yellow },
		SpecialChar = { fg = colors.yellow },
		Tag = { fg = colors.yellow },
		Delimiter = { fg = colors.pink },
		SpecialComment = { link = "Keyword" },
		Debug = { link = "Keyword" },
		Underlined = { fg = colors.cyan, underline = true },
		Ignore = {},
		Error = { fg = colors.diag_error },
		Todo = { fg = colors.cyan, bold = true },
	}
end

return M
